Fix be_installed matcher when used with expect
When used like

  expect(package('httpd')).to be_installed

it causes an error that subject is not defined

  undefined local variable or method `subject' for
  #<RSpec::Matchers::DSL::Matcher be_installed> (NameError)

It should be changed to use the passed #match parameter 'name'
instead of 'subject'.